export const APP_CONSTANTS = {
  PASSWORD_MIN_LENGTH: 8,

  ACCESS_TOKEN_EXPIRES_IN: "15m",

  REFRESH_TOKEN_EXPIRES_IN: "7d",

  PASSWORD_RESET_TOKEN_EXPIRES_IN_MINUTES: 30,

  EMAIL_VERIFICATION_TOKEN_EXPIRES_IN_HOURS: 24,
} as const;
